### PR TITLE
data.gof in different location

### PR DESCRIPTION
**Pull request by ghost**
ERROR fixed:
~~~
IRISAPP>do ##class(I2B2.FHIR.Install).LoadDefData("/opt/irisbuild/dataset/data.gof")
Loading test data, this may take timeERROR #5001: Global Restore aborted.
Unable to open device!
subs=?
data=?
IRISAPP>
~~~

### CODE REVIEW

**Comment by ELynx** [comment]
Thanks for noticing!

In Dockerfile I used

```
COPY dataset dataset
RUN tar -xf /opt/irisbuild/dataset/data.gof.tar.gz
```

So I expect that final path is indeed `/opt/irisbuild/dataset/data.gof`

I checked just now with my local build, and I have this too now. Must have been working before because I had leftover files from before compression.

I will look into this one ASAP.

**Comment by ELynx** [comment]
I have worked on this issue locally, and now it works for me even with clear cache. I have my fixes committed to master now. Issue was with missing tar command argument.

I also removed base image update and git installation, since it took too much time but was not used later on.

Please test if this works for you as well.

**Comment by ELynx** [comment]
Also if this is still broken, please make an issue, development team and I will work this out in our workflow.

**Comment by rcemper** [comment]
I can confirm it is fixed. Thanks !
~~~
IRISAPP>do ##class(I2B2.FHIR.Install).LoadDefData("/opt/irisbuild/dataset/data.gof")
Loading test data, this may take time
Test data loaded successfully

IRISAPP>
~~~

**Pull request closed without merging**
